### ISSUE TITLE
Step duplicates artifact files

### ISSUE THREAD

**Issue by G00fY2** [bitrise-steplib/steps-gradle-runner#72]
Here is the output for our assemble and bundle task:
```
Move APK and AAB files...
copy app/build/intermediates/intermediary_bundle/productionStoreRelease/app-production-store-release.aab to /bitrise/deploy/app-production-store-release.aab
copy app/build/outputs/apk/productionStore/release/myapp-app-productionStoreRelease.apk to /bitrise/deploy/myapp-app-productionStoreRelease.apk
  1 attempt failed:
file already exists at: /bitrise/deploy/app-production-store-release.aab
  Retrying...
copy app/build/outputs/bundle/productionStoreRelease/app-production-store-release.aab to /bitrise/deploy/app-production-store-release20200513235957.aab
```
As you can see there seems to be a timing issue when moving files to the bitrise path.

We face this issue every build.

**Comment by bitce** [comment]
Hi @G00fY2! Can you please include an URL to any of these builds?

**Comment by G00fY2** [comment]
It's private not sure if you can access it: https://app.bitrise.io/build/e302c8e56372a361#

**Comment by koral--** [comment]
@bitce FYI this was already reported on discuss: https://discuss.bitrise.io/t/file-already-exists-error-when-building-aab/9983/5

**Comment by non-binary** [comment]
Hi @koral--,

The Bitrise community forum is primarily for the community to help each other. It is not a main method of accessing support for Bitrise, which is why some tickets go unanswered.

I highly recommend you creating a GH issue for bugs and those types of issues and a support ticket through for all other requests: https://www.bitrise.io/bitrise-support.

Thanks,
Luna

**Comment by koral--** [comment]
I know that.
I've added that comment mainly for @bitce so he can get more build examples if he don't recall that ticket on discuss :)

**Comment by bitce** [comment]
That's correct, thanks @koral--! we have an item in our backlog for this, we'll do what we can to bump the priority.

**Comment by koral--** [comment]
@bitce How it is going? Is there any update on this?

**Comment by bitce** [comment]
There is no progress on this just yet unfortunately, we'll make sure to let everyone know here once there is!

**Comment by koral--** [comment]
Any ETA on this?
This issue in conjunction https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/93 combines to very weird result. Those redundant AABs gets all converted to universal APKs which result in confusion for QAs and other people using bitrise.io public installation page.

**Comment by G00fY2** [comment]
I'm also surprised that the priority this issue seems so low. This ticket was opened more the 24 weeks ago. And it's really annoying that bitrise messing up the saved artifacts.

6x mapping file:
```Move mapping files...
copy app/build/outputs/mapping/...-release-mapping.txt to /bitrise/deploy/...-release-mapping.txt

copy app/build/outputs/mapping/...mapping.txt to /bitrise/deploy/mapping.txt

copy app/build/tmp/compile...JavaWithJavac/source-classes-mapping.txt to /bitrise/deploy/source-classes-mapping.txt
  1 attempt failed:
file already exists at: /bitrise/deploy/source-classes-mapping.txt
  Retrying...

copy .../build/tmp/compileJava/source-classes-mapping.txt to /bitrise/deploy/source-classes-mapping20200831135813.txt
  1 attempt failed:
file already exists at: /bitrise/deploy/source-classes-mapping.txt
  Retrying...

copy .../build/tmp/compileJava/source-classes-mapping.txt to /bitrise/deploy/source-classes-mapping20200831135814.txt
  1 attempt failed:
file already exists at: /bitrise/deploy/source-classes-mapping.txt
  Retrying...

copy .../build/tmp/compileJava/source-classes-mapping.txt to /bitrise/deploy/source-classes-mapping20200831135815.txt
  1 attempt failed:
file already exists at: /bitrise/deploy/source-classes-mapping.txt
  Retrying...

copy .../build/tmp/compileJava/source-classes-mapping.txt to /bitrise/deploy/source-classes-mapping20200831135816.txt
  1 attempt failed:
file already exists at: /bitrise/deploy/source-classes-mapping.txt
  Retrying...

copy .../build/tmp/compileJava/source-classes-mapping.txt to /bitrise/deploy/source-classes-mapping20200831135817.txt```

**Comment by malenalbc** [comment]
Hi, this is happening to me too with Gradle Runner 1.9.6:

```
Move APK and AAB files...
copy app/build/intermediates/intermediary_bundle/<flavor>Release/<flavor>release.aab to /bitrise/deploy/<flavor>release.aab
  1 attempt failed:
file already exists at: /bitrise/deploy/<flavor>release.aab
  Retrying...
copy app/build/outputs/bundle/<flavor>Release/<flavor>release.aab to /bitrise/deploy/<flavor>release20210219141525.aab
The app path is now available in the Environment Variable: $BITRISE_AAB_PATH (value: /bitrise/deploy/<flavor>release20210219141525.aab)
The app paths list is now available in the Environment Variable: $BITRISE_AAB_PATH_LIST (value: /bitrise/deploy/<flavor>release.aab|/bitrise/deploy/<flavor>release20210219141525.aab)
No file name matched test apk filters
Move mapping files...
copy app/build/outputs/mapping/<flavor>Release/mapping.txt to /bitrise/deploy/mapping.txt
The mapping path is now available in the Environment Variable: $BITRISE_MAPPING_PATH (value: /bitrise/deploy/mapping.txt)
```

What's concerning is that, adding the Deploy to Bitrise step 1.13.0, and checking Apps&Artifacts, files `<flavor>release.aab` (19.47 MB) and `<flavor>release20210219141525.aab` (19.57 MB) are not the same size.

**Comment by ofalvai** [comment]
For those who still experience this bug, can you please provide more info about your workflow? Things like:
- Your Gradle Runner step config. Did you make changes to the default values?
- Your project setup: Do you have multiple modules or just an `app` module?
- Does this happen in every build, or just once in a while?
- What happens if you replace the Gradle Runner step with one of our dedicated Android steps? ([Android Build](https://www.bitrise.io/integrations/steps/android-build) / [Android Build for UI testing](https://www.bitrise.io/integrations/steps/android-build-for-ui-testing))

**Comment by G00fY2** [comment]
The issue didn't appear in our builds for a while now. So I can't reproduce it anymore.

I can't tell what exactly changed, since obviously we updated Gradle, the Android Plugin, the Build Steps and so on.

**Comment by shuo651197769** [comment]
@ofalvai Hi, I am having this issue as well

I just run bundleRelease job, not changing any default value. And I have 3 modules and it happens every time.

**Comment by ofalvai** [comment]
@shuo651197769 can you please open [a new request](https://support.bitrise.io/requests/new) in our support center? Debugging this will probably need some back and forth messaging and enabling support access for the affected project in Bitrise. Thanks!

**Comment by mateherber** [comment]
Analyzing the reports here also on our community forums I concluded that the step did have the wrong order of log messages printed which made understanding what was going on really hard.

Most (if not all) reports are because the `*.apk` or `*.aab` files are also considered in the `.../immediate/...` directory had the same name as the final archive. This is no longer the case for the newer version of the Android Gradle Plugin, that is the reason we get fewer reports of this issue.

To tackle this we improved on the logging in `2.0.1` version of the step, also introduced several temporary/immediate paths to the default exclusion list to help our users.

As always, should you experience any further problems, please open a new issue for us!
